# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  exercise09-environment_variables:
    jobs:
      - print_env_var

jobs:
  print_env_var:
    docker:
      - image: alpine/alpine:3.14.1
    steps:
      - checkout
      - run:
          name: "Print an environment variable from this project"
          command: |
            echo $MY_CURRENT_ENV_VAR
